### ISSUE TITLE
Unable to see any highlighting

### ISSUE THREAD

**Issue by eivindmjelde** [danwhite85/vscode-mustache-syntax-highlighting#1]
Hi! Been missing .mustache highlighting in Code for a while now, so I was exited to see an extension that added this. I've installed the extension and reloaded the editor, but I am still unable to see any highlighting.

Does the extension require any further configuration?

**Comment by dnwhte** [comment]
Hi @eivindmjelde 

It shouldn't require any configuration. Is the language for your file set to "Mustache (HTML)"? VS Code should automatically set the language, but I have had issues where other extensions or user settings cause issues with that.

**Comment by eivindmjelde** [comment]
Think I've found the issue. I usually like to put a whitespace after the hash and backslash in sections to make it more readable (i.e. `{{# sectionName }}` instead of `{{#sectionName}}`). Once I removed this whitespace I was able to see the highlighting.

**Comment by dnwhte** [comment]
Interesting. Any idea on how to go about supporting both?

**Comment by eivindmjelde** [comment]
Unfortunately I don't have any experience working with language 'colorizers', but I wouldn't mind having a look at it if I can find some spare time.

There's also a couple of irks (for me) when setting the language to "Mustache (HTML)". Seems like neither Beautify (code formatting) or Emmet will work when using this language. But I suspect that this might not be too hard to fix (just getting these extensions to handle .mustache-files as html)?

**Comment by pnBenY** [comment]
@eivindmjelde Did you manage to get code formatting or emmet working?

**Comment by dnwhte** [comment]
@eivindmjelde @pnBenY, have you tried adding mustache to emmet.includelanguages?
```
"emmet.includeLanguages": {
      "mustache": "html"
}
```

**Comment by dnwhte** [comment]
@eivindmjelde you could try adding mustache to beautify as well. 
```
"beautify.language": {
    "html": {
        "ext": [
            "html",
            "htm",
            "mustache"
        ]
    }
}
```

**Comment by sandrojohanides** [comment]
@danwhite85 
> Interesting. Any idea on how to go about supporting both?

Looking at `mustache.tmLanguage`, probably by fixing the regexes, eg. `<string>\{\{\s*(#|\^)[A-Za-z0-9_.]+\s*\}\}</string>` to also allow whitespaces after the block/not/include token but before the `[A-Za-z0-9_.]` set. Would make a pull request but I have no tm lang grammar skills, so I’m not sure if it’s the correct solution.

Until now I've used `SublimeHTMLMustache` and it looks like they’re using a different solution, have a look @ https://github.com/adamchainz/SublimeHTMLMustache/blob/master/Syntaxes/HTMLMustache.tmLanguage

**Comment by dnwhte** [comment]
Just releases 1.1.1 that supports whitespace in the tags as well as better highlighting for comments. Eventually I'd like to learn more about tmlanguage and make this package better.
