### ISSUE TITLE
Combining VS Code intellisense with Mustache highlighting

### ISSUE THREAD

**Issue by lenkan** [danwhite85/vscode-mustache-syntax-highlighting#5]
Thanks for providing this extension.

When I set the file language mode to `HTML`. I get the default VS Code html highlighting, _with_ intellisense, but of course _without_ mustache highlighting. As such: 

![Screenshot from 2019-04-07 12-40-14](https://user-images.githubusercontent.com/5889538/55682370-de0ad700-5932-11e9-8b0d-bf760aa2b3ee.png)

This feature disappears when setting the language mode to `Mustache (HTML)`. Do you know if it is possible to combine these?

I'd be happy to help in implementing, but since I am pretty clueless about VS Code extensions, I thought I'd check if you can give some indication about what may cause this?

**Comment by dnwhte** [comment]
I'm not sure about combining. Why the need to set the language mode to HTML?

The only issue I've run into is that emmet wasn't working on mustache files. In that case you have to tell emmet how to treat mustache files.

```
    "emmet.includeLanguages": {
      "mustache": "html"
    }
```
